### ISSUE TITLE
This lab is missing tests

### ISSUE THREAD

**Issue by Lukeghenco** [learn-co-curriculum/css-manifests-lab#2]
This lab only has the tests in the solution branch. And when you fork it using learn open it defaults to the cd/first draft branch.

**Comment by onyoo** [comment]
The lab also seems to be in another repo.
<img width="185" alt="screen shot 2016-02-23 at 1 32 58 pm" src="https://cloud.githubusercontent.com/assets/14326883/13251677/fed59fb6-da31-11e5-8ae0-0a36937110cd.png">

**Comment by onyoo** [comment]
Relating to the tests, the configuration pointed-out above prevents the tests from being run:

<img width="1225" alt="screen shot 2016-02-23 at 1 36 48 pm" src="https://cloud.githubusercontent.com/assets/14326883/13251825/b8e33cf6-da32-11e5-8292-ea2a05aec6fc.png">

but if we cd into the `css_manifest_rails/` repo, they do run:

```
// ♥ learn
This directory doesn't appear to have any specs in it.
[13:44:25] (master) css-manifests-lab-v-000
// ♥ cd css_manifest_rails/
[13:44:39] (master) css_manifest_rails
// ♥ rspec
FFFFFF.F

Failures:

  1)  should include the main file in the admin layout
```

**Comment by AnnJohn** [comment]
thanks @Lukeghenco and @onyoo, this looks similar to the other one having tests in another branch. Will update this as soon as we can.
